---
title: "p8105_hw3_ay2452"
author: "Alicia Yang"
date: "10/14/2019"
output: github_document
---

```{r Problem 1.1}
library(tidyverse)
library(p8105.datasets)
 
data("instacart")

instacart %>%
  janitor::clean_names() %>%
  group_by(aisle) %>%
  summarize( 
    n_obs = n()) %>% view
    
##The "instacart" dataset has 1384617 observations and 15 variables. Key variables include the order id, user id, time of order (both by day of the week and hour of day), product ordered, product department, aisle, and their associated ids. As is, the dataset is structured so that items in an order are grouped together.
##There are 134 total aisles. Aisles from which the most items are ordered from are (in descending order): fresh veggies, fresh fruits, packaged vegatble fruits, yogurt, and packaged cheese.
```

```{r Problem 1.2}
instacart %>%
  group_by(aisle) %>%
  summarize( 
    n_obs = n()) %>%
  filter(
    n_obs > 10000
  ) %>%
  ggplot(aes(x = reorder(aisle, n_obs), y = n_obs)) + 
  geom_bar(stat = "identity") + coord_flip() + labs(
    title = "Number of Items Ordered from Aisles in Instacart", 
    x = "Aisle", 
    y = "Observations"
  ) %>% view

##The plot shows the different aisles and the number of items ordered from each aisle in descending order from the top. Fresh vegetables and fresh fruits are very close and greatly outnumber the other aisles. 
```

```{r Problem 1.3}
instacart %>%
  filter(aisle == c("baking_ingredients","dog_food_care","packaged_vegetable_fruits")) %>%
  group_by(aisle, product_name) %>%
  summarize( 
    n_obs = n()) %>%
  filter(min_rank(desc(n))<4) %>%
  knitr::kable(col.names = c("Aisle", "Product", "Number"))

##Created table looking at three most popular items in each of the specified aisls.  
```
```{r Problem 1.4}
instacart %>%
  filter(product_name %in% c("Pink Lady Apple", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(
    mean_hr_day = mean(order_hour_of_day)) %>%
  pivot_wider(
    names_from = "order_dow", 
    values_from = "mean_hr_day") %>%
  knitr::kable(col.names = c("Product", 
                             "Sunday", 
                             "Monday", 
                             "Tuesday", 
                             "Wednesday", 
                             "Thursday", 
                             "Friday", 
                             "Saturday"))

##The 2x7 table shows the mean hour of day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week. Coffee Ice Cream seems to be ordered most between 1-3 pm and Pink Lady Apples mostly between 1-4 pm (although Wednesday is a bit different with a mean of 8 am).
```

```{r Problem 2.1}
data("brfss_smart2010")

brfss_smart2010 %>%
  filter(Response == c("Poor", "Fair", "Good", "Very Good", "Excellent")) %>%
  mutate(Response = ordered(Response, c("Poor", "Fair", "Good", "Very Good", "Excellent"))) %>%
  janitor::clean_names()

##Cleaning the brfss_smart2010 dataset by focusing on the "Overall Health" topic and including responses from "Excellent" to "Poor". Responses were also ordered from "Poor" to "Excellent" and variable names are formatted appropiately.
```

```{r Problem 2.2a Year 2002}
brfss_smart2010 %>%
  filter(Year == "2002") %>%
  group_by(Year, Locationabbr) %>%
  summarize(n_obs = n()) %>%
  filter(n_obs > 6)

##In 2002, states that were observed at 7 or more locations included: AK, AL, AR, AZ, CA, CO, CT, DC, DE, FL, GA, HI, IA, ID, IL, IN, KS, KY, LA, MA, MD, ME, MI, MN, MO, MS, NC, ND, NE, NH, NJ, NM, NV, NY, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VT, WA, WI, WV, and WY. 
```

```{r Problem 2.2b Year 2010}
brfss_smart2010 %>%
  filter(Year == "2010") %>%
  group_by(Year, Locationabbr) %>%
  summarize(n_obs = n()) %>%
  filter(n_obs > 6)

##In 2002, states that were observed at 7 or more locations included: AL, AR, AZ, CA, CO, CT, DC, DE, FL, GA, HI, IA, ID, IL, IN, KS, KY, LA, MA, MD, ME, MI, MN, MO, MS, MT, NC, ND, NE. NH, NJ, NM, NV, NY, OH, OK, OR, PA, RI, SC, SD. TN, TX, UT, VT, WA, WI, WV, and WY. 
```

```{r Problem 2.3}
brfss_1 =
brfss_smart2010 %>%
  filter(Response == "Excellent") %>%
  group_by(Year, Locationabbr) %>%
  summarize(Data_mean = mean(Data_value))

brfss_1 %>%
  ggplot(aes(x = Year, y = Data_mean)) + 
  geom_line(aes(group = Locationabbr, color = Locationabbr)) + labs(
    title = "State Excellent Responses by Year", 
    x = "Year", 
    y = "Responses"
  )

##Created a new dataset, "brfss_1" and plotted a spaghetti graph with each state having its own color. 3 rows were removed due to missing values. 
```


